dags:
  gitSync:
    enabled: true
    repo: git@github.com:lucasudar/kubernetes_surfalytics.git
    branch: master
    subPath: ""
    sshKeySecret: airflow-ssh-secret
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDZmg1YmdpajN6aXdhTlo0N2lHbVJCNnkrWlVuUlY4S1JQL3ptZzRjQktUUUFBQUtpdGpra2xyWTVKCkpRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ2ZoNWJnaWozeml3YU5aNDdpR21SQjZ5K1pVblJWOEtSUC96bWc0Y0JLVFEKQUFBRUFvRzRCK0toaWZqMUxrSFBOdklJck9RcC8rdkdxdTZncndvSStoNjh2MFo1K0hsdUNLUGZPTEJvMW5qdUlhWkVIcgpMNWxTZEZYd3BFLy9PYURod0VwTkFBQUFKRjlzZFdOaGMxOUFUbWxyYVhSaGN5MU5ZV05DYjI5ckxVRnBjaTFOTVM1c2IyCk5oYkFFPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K'